openapi: 3.0.3
info:
  title: Interview Assistant Backend API
  description: API for an interview assistant extension that accepts HTML code, screenshots, programming language, prompts, and optional voice recordings, processes them with a local LLM (via Ollama), and returns the results.
  version: 1.0.1
servers:
  - url: http://127.0.0.1:8000
    description: Local development server
paths:
  /:
    get:
      summary: Health check
      description: Returns a simple message to confirm the backend is running.
      operationId: getRoot
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Interview Assistant Backend is running
  /upload:
    post:
      summary: Upload data and process with LLM
      description: Accepts multipart form data with HTML code, a screenshot (image file), programming language, prompt, and an optional voice recording (audio file). Stores the data, processes text inputs with a local LLM, and returns a session ID, status message, and LLM response.
      operationId: uploadData
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - html_code
                - programming_language
              properties:
                html_code:
                  type: string
                  description: HTML code of the page as a string.
                  example: "<html><body><h1>Test Page</h1></body></html>"
                programming_language:
                  type: string
                  description: Programming language used (e.g., Python, JavaScript).
                  example: python
      responses:
        '200':
          description: Successful upload and LLM processing
          content:
            application/json:
              schema:
                type: object
                required:
                  - session_id
                  - message
                properties:
                  session_id:
                    type: string
                    format: uuid
                    description: Unique UUID for the uploaded data session.
                    example: 550e8400-e29b-41d4-a716-446655440000
                  message:
                    type: string
                    description: Status message indicating success.
                    example: Data uploaded and LLM processed successfully
                  llm_response:
                    type: string
                    nullable: true
                    description: Response from the local LLM (e.g., generated text) or an error message if LLM processing fails.
                    example: Here is a function to reverse a string...
        '400':
          description: Bad request (e.g., invalid file type for screenshot or voice recording)
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: Screenshot must be an image
        '500':
          description: Server error (e.g., file system or database issues)
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: Error processing upload
components:
  schemas: {}